### ISSUE TITLE
The last published version (0.3.0) includes inconsistent duration_since

### ISSUE THREAD

**Issue by loyd** [maidsafe/sn_fake_clock#22]
Why isn't https://github.com/maidsafe/fake_clock/commit/cee4944de3ff6e9f346465f8f36b904b39090364 published?

**Comment by MingweiSamuel** [comment]
Wait, shouldn't `duration_since` take in `&self`? That's what `Instant` has: https://doc.rust-lang.org/std/time/struct.Instant.html#method.duration_since

**Comment by loyd** [comment]
> Wait, shouldn't duration_since take in &self?

Exactly. I don't understand why the master version contains `duration_since(self)`
